### ISSUE TITLE
responsive layout breaking in posts due to long inline code blocks

### ISSUE THREAD

**Issue by thephilgray** [thephilgray/thephilgray-gatsby#5]
## Description

<a href="https://cl.ly/dcd9315b9b0d" target="_blank"><img src="https://duaw26jehqd4r.cloudfront.net/items/353y0E2t0g0C3g120v1V/%5Bc7011a591452999296ed57c47154d7ad%5D_Image+2019-01-17+at+9.15.29+AM.png" style="display: block;height: auto;width: 100%;"/></a>

## Solution

Apply `word-break: break-word;` to global styles: 

```css
:not(pre)>code[class*=language-]{
    word-break: break-word;
  }
  
```
